/**
 * 面板静态注册表 - Vue 面板的 UI 元数据
 * 面板 id 是前端状态/路由身份；旧 Python service 名称只在兼容边界中保留。
 */
export const PLUGIN_MANIFEST = [
  {
    id: 'SceneTools',
    routePath: '/SceneBar',
    displayNameKey: 'plugins.SceneTools',
    displayName: '场景管理',
    pageType: 'view',
    defaultDock: 'right',
    defaultWidth: 360,
    defaultHeight: 540,
    autoInit: false,
    defaultOpenMode: 'docked',
    defaultFloatPosition: 'right_top',
    minFloatWidth: 340,
    minFloatHeight: 360,
    floatingPriority: 10,
  },
  {
    id: 'LightFieldCalibration',
    routePath: '/LightFieldCalibration',
    displayNameKey: 'plugins.LightFieldCalibration',
    displayName: '光场3D UI标定',
    pageType: 'view',
    defaultDock: 'right',
    defaultWidth: 300,
    defaultHeight: 300,
    autoInit: false,
  },
  {
    id: 'Object',
    routePath: '/Object',
    displayNameKey: 'plugins.Object',
    displayName: '对象',
    pageType: 'view',
    defaultDock: 'right',
    defaultWidth: 360,
    defaultHeight: 540,
    autoInit: false,
    defaultOpenMode: 'docked',
    defaultFloatPosition: 'right_bottom',
    minFloatWidth: 320,
    minFloatHeight: 320,
    floatingPriority: 10,
  },
  {
    id: 'AITool',
    routePath: '/Pet',
    displayNameKey: 'plugins.AITool',
    displayName: '白菜助手',
    pageType: 'plugin',
    defaultDock: 'bottom',
    defaultWidth: 200,
    defaultHeight: 200,
    autoInit: false,
  },
  {
    id: 'LogTool',
    routePath: '/LogView',
    displayNameKey: 'plugins.LogTool',
    displayName: '日志工具',
    pageType: 'view',
    defaultDock: 'bottom',
    defaultWidth: 1100,
    defaultHeight: 200,
    autoInit: false,
  },
  {
    id: 'FileManager',
    routePath: '/FileManager',
    displayNameKey: 'plugins.FileManager',
    displayName: '文件管理器',
    pageType: 'view',
    defaultDock: 'left',
    defaultWidth: 300,
    defaultHeight: 600,
    autoInit: false,
  },
  {
    id: 'ProjectSettings',
    routePath: '/ProjectSettings',
    displayNameKey: 'plugins.ProjectSettings',
    displayName: '项目设置',
    pageType: 'special',
    defaultDock: 'center',
    defaultWidth: 600,
    defaultHeight: 800,
    autoInit: false,
  },
  {
    id: 'NodeGraphPanel',
    routePath: '/NodeGraph',
    displayNameKey: 'plugins.NodeGraphPanel',
    displayName: '节点',
    pageType: 'view',
    defaultDock: 'bottom',
    // Open wide enough for the toolbox, node canvas and inspector to use the
    // normal three-column layout immediately. Narrower user-resized windows still
    // fall back to NodeGraphWorkspace's compact responsive layout.
    defaultWidth: 1100,
    defaultHeight: 320,
    // Keep the docked height compact, but open the shortcut-created floating panel
    // at the large centered size used by the node editing workflow.
    defaultFloatWidth: 1480,
    defaultFloatHeight: 790,
    autoInit: false,
    defaultOpenMode: 'docked',
    defaultFloatPosition: 'center',
    minFloatWidth: 760,
    minFloatHeight: 440,
    floatingPriority: 100,
  },
  {
    id: 'CabbageChatPanel',
    routePath: '/CabbageChat',
    displayNameKey: 'plugins.CabbageChatPanel',
    displayName: 'AI 创作助手',
    pageType: 'plugin',
    defaultDock: 'right',
    defaultWidth: 420,
    defaultHeight: 600,
    autoInit: false,
    defaultOpenMode: 'docked',
    defaultFloatPosition: 'right_bottom',
    minFloatWidth: 340,
    minFloatHeight: 400,
    floatingPriority: 110,
  },
  {
    id: 'EditorSettings',
    routePath: '/SetUp',
    displayNameKey: 'plugins.EditorSettings',
    displayName: '暂停菜单',
    pageType: 'special',
    defaultDock: 'center',
    defaultWidth: 620,
    defaultHeight: 720,
    autoInit: false,
  },
  {
    id: 'Network',
    routePath: '/Network',
    displayNameKey: 'plugins.Network',
    displayName: '局域网聊天',
    pageType: 'plugin',
    defaultDock: 'right',
    defaultWidth: 360,
    defaultHeight: 430,
    autoInit: false,
  },
];

/** 按 id 快速查找 */
export function getPluginManifest(id) {
  return PLUGIN_MANIFEST.find((p) => p.id === id);
}
