/** Compatibility scene facade for external panels and older integrations. */

import { editorApi } from '../api/editorApi.js';

export const sceneService = {
  removeActor: (sceneName, actorName) => editorApi.sceneTools.removeActor(sceneName, actorName),
  renameActor: (sceneName, actorName, name) => editorApi.sceneTools.renameActor(sceneName, actorName, name),
  createScene: (sceneName) => editorApi.main.createScene(sceneName),
  sunDirection: (sceneName, enable, direction) => editorApi.sceneTools.sunDirection(sceneName, enable, direction),
  floorGrid: (sceneName, enabled) => editorApi.sceneTools.floorGrid(sceneName, enabled),
  setPhysicsParams: (sceneName, params) => editorApi.sceneTools.setPhysicsParams(sceneName, params),
  getPhysicsParams: (sceneName) => editorApi.sceneTools.getPhysicsParams(sceneName),
  selectScreenshotPath: (sceneName, cameraName) => editorApi.sceneTools.selectScreenshotPath(sceneName, cameraName),
  saveScreenshot: (sceneName, path, cameraName) => editorApi.sceneTools.saveScreenshot(sceneName, path, cameraName),
  setOutputMode: (sceneName, cameraName, mode) => editorApi.sceneTools.setOutputMode(sceneName, cameraName, mode),
  getOutputMode: (sceneName, cameraName) => editorApi.sceneTools.getOutputMode(sceneName, cameraName),
  setShadowCascadeDebug: (sceneName, cameraName, enabled) => editorApi.sceneTools.setShadowCascadeDebug(sceneName, cameraName, enabled),
  getShadowCascadeDebug: (sceneName, cameraName) => editorApi.sceneTools.getShadowCascadeDebug(sceneName, cameraName),
  setSsaoEnabled: (sceneName, cameraName, enabled) => editorApi.sceneTools.setSsaoEnabled(sceneName, cameraName, enabled),
  getSsaoEnabled: (sceneName, cameraName) => editorApi.sceneTools.getSsaoEnabled(sceneName, cameraName),
  isVisionAvailable: () => editorApi.sceneTools.isVisionAvailable(),
  setRenderBackend: (mode, sceneName = null, cameraId = null) => editorApi.sceneTools.setRenderBackend(mode, sceneName, cameraId),
  getRenderBackend: (sceneName = null, cameraId = null) => editorApi.sceneTools.getRenderBackend(sceneName, cameraId),
  setVisionRenderMode: (sceneName, cameraId = null, mode = 'path_tracing') => editorApi.sceneTools.setVisionRenderMode(sceneName, cameraId, mode),
  getVisionRenderMode: (sceneName, cameraId = null) => editorApi.sceneTools.getVisionRenderMode(sceneName, cameraId),
  createCameraView: (sceneName, name = null) => editorApi.sceneTools.createCameraView(sceneName, name),
  openCameraView: (sceneName, cameraId) => editorApi.sceneTools.openCameraView(sceneName, cameraId),
  closeCameraView: (sceneName, cameraId) => editorApi.sceneTools.closeCameraView(sceneName, cameraId),
  renameCameraView: (sceneName, cameraId, name) => editorApi.sceneTools.renameCameraView(sceneName, cameraId, name),
  listCameraViews: (sceneName) => editorApi.sceneTools.listCameraViews(sceneName),
  updateCameraView: (sceneName, cameraId, state) => editorApi.sceneTools.updateCameraView(sceneName, cameraId, state),
  deleteCamera: (sceneName, cameraId) => editorApi.sceneTools.deleteCamera(sceneName, cameraId),
  loadVisionScene: (path) => editorApi.sceneTools.loadVisionScene(path),
  reloadScene: (sceneName, projectPath = '') => editorApi.sceneTools.reloadScene(sceneName, projectPath),
  rebindActorResource: (sceneName, actorGuid, path) => editorApi.sceneTools.rebindActorResource(sceneName, actorGuid, path),
  openSceneActor: (sceneName, actorName) => editorApi.sceneTools.openActor(sceneName, actorName),
  setActorState: (sceneName, actorName, state) => editorApi.sceneTools.setActorState(sceneName, actorName, state),
  selectModelFileDialog: (sceneName, actorName, fileType = 'model') => editorApi.sceneTools.selectModelFile(sceneName, actorName, fileType),
  setActorCameraLock: (sceneName, actorName, cameraLock) => editorApi.sceneTools.setActorCameraLock(sceneName, actorName, cameraLock),
  pickActor: (sceneName, x, y, vpWidth, vpHeight) => editorApi.sceneTools.pickActor(sceneName, x, y, vpWidth, vpHeight),
  playAudio: (resourceId, loop) => editorApi.sceneTools.playAudio(resourceId, loop),
  stopAudio: (resourceId) => editorApi.sceneTools.stopAudio(resourceId),
  actorPlayAudio: (actorName, loop = false) => editorApi.sceneTools.actorPlayAudio(actorName, loop),
  actorStopAudio: (actorName) => editorApi.sceneTools.actorStopAudio(actorName),
  getScene: (sceneId) => editorApi.scene.getSnapshot(sceneId),
  /** @deprecated Script Runtime and old-host compatibility only. */
  actorOperation: (scene_name, actor_name, operation, vector) => editorApi.sceneDatas.actorOperation(scene_name, actor_name, operation, vector),
};
