if(NOT DEFINED TEST_DIRECTORY OR NOT DEFINED REPO_ROOT)
    message(FATAL_ERROR "Test paths are required")
endif()
set(STARTUP_CONFIG_SOURCE "${REPO_ROOT}/CoronaEngine.default.json")
set(STARTUP_CONFIG_DESTINATION "${TEST_DIRECTORY}/CoronaEngine.json")
file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
file(REMOVE "${STARTUP_CONFIG_DESTINATION}")
include("${REPO_ROOT}/cmake/corona_seed_startup_config.cmake")
file(READ "${STARTUP_CONFIG_SOURCE}" expected)
file(READ "${STARTUP_CONFIG_DESTINATION}" actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "First deployment must seed the default configuration")
endif()
set(local_config "{\"profiling\":{\"switch_profile\":true}}")
file(WRITE "${STARTUP_CONFIG_DESTINATION}" "${local_config}")
include("${REPO_ROOT}/cmake/corona_seed_startup_config.cmake")
file(READ "${STARTUP_CONFIG_DESTINATION}" actual)
if(NOT actual STREQUAL local_config)
    message(FATAL_ERROR "Rebuilding must preserve local configuration changes")
endif()
